# Generated by Django 5.1.6 on 2025-03-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=63)),
                ('first_name', models.CharField(max_length=63)),
                ('patronymic', models.CharField(max_length=63, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.executor')),
            ],
        ),
    ]
