# Generated by Django 5.1.6 on 2025-03-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0002_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='related_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.executor'),
        ),
    ]
