# Generated by Django 5.1.6 on 2025-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
                ('company_fullName', models.CharField(default=models.CharField(max_length=64), max_length=256)),
                ('director_post', models.CharField(default='Директор', max_length=32)),
                ('director_username', models.CharField(max_length=64)),
                ('contractor_city', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
                ('company_fullName', models.CharField(default=models.CharField(max_length=64), max_length=256)),
                ('director_post', models.CharField(default='Директор', max_length=32)),
                ('director_username', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
