# Generated by Django 5.1.6 on 2025-03-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('company_username', models.CharField(default='company938', max_length=32, primary_key=True, serialize=False, verbose_name='Логин')),
                ('company_name', models.CharField(max_length=64)),
                ('company_fullName', models.CharField(default=models.CharField(max_length=64), max_length=256)),
                ('director_post', models.CharField(default='Директор', max_length=32, verbose_name='Должность директора')),
                ('director_last_name', models.CharField(max_length=63, null=True, verbose_name='Фамилия директора')),
                ('diretor_first_name', models.CharField(max_length=63, null=True, verbose_name='Имя директора')),
                ('director_patronymic', models.CharField(max_length=63, null=True, verbose_name='Отчество директора')),
                ('contractor_city', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('company_username', models.CharField(default='company938', max_length=32, primary_key=True, serialize=False, verbose_name='Логин')),
                ('company_name', models.CharField(max_length=64)),
                ('company_fullName', models.CharField(default=models.CharField(max_length=64), max_length=256)),
                ('director_post', models.CharField(default='Директор', max_length=32, verbose_name='Должность директора')),
                ('director_last_name', models.CharField(max_length=63, null=True, verbose_name='Фамилия директора')),
                ('diretor_first_name', models.CharField(max_length=63, null=True, verbose_name='Имя директора')),
                ('director_patronymic', models.CharField(max_length=63, null=True, verbose_name='Отчество директора')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('company_username', models.CharField(default='company816', max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Логин')),
                ('company_name', models.CharField(max_length=64)),
                ('company_fullName', models.CharField(default=models.CharField(max_length=64), max_length=256)),
                ('director_post', models.CharField(default='Директор', max_length=32, verbose_name='Должность директора')),
                ('director_last_name', models.CharField(max_length=63, null=True, verbose_name='Фамилия директора')),
                ('diretor_first_name', models.CharField(max_length=63, null=True, verbose_name='Имя директора')),
                ('director_patronymic', models.CharField(max_length=63, null=True, verbose_name='Отчество директора')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
