# Generated by Django 5.1.6 on 2025-03-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='company_username',
            field=models.CharField(default='company260', max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='company_username',
            field=models.CharField(default='company741', max_length=32, primary_key=True, serialize=False, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='company_username',
            field=models.CharField(default='company741', max_length=32, primary_key=True, serialize=False, verbose_name='Логин'),
        ),
    ]
