# Generated by Django 5.1.6 on 2025-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companyuser_company_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='company_username',
            field=models.CharField(default='company656', max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='company_username',
            field=models.CharField(default='company683', max_length=32, primary_key=True, serialize=False, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='company_username',
            field=models.CharField(default='company683', max_length=32, primary_key=True, serialize=False, verbose_name='Логин'),
        ),
    ]
