# Generated by Django 5.1.6 on 2025-04-05 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', 'initial_fields_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='id',
        ),
        migrations.AlterField(
            model_name='field',
            name='englName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Английское название поля (по которому будет доступ в API)'),
        ),
        migrations.CreateModel(
            name='UsersValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_field', to='backend.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
    ]
