# Generated by Django 5.1.6 on 2025-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Русское название поля (для отображения)')),
                ('englName', models.CharField(max_length=50, verbose_name='Английское название поля (по которому будет доступ в API)')),
                ('relatedItem', models.CharField(editable=False, max_length=30, verbose_name='К какому виду записи относится это поле (заполняется программно)')),
                ('type', models.CharField(choices=[('TEXT', 'Текстовое поле'), ('PASSWORD', 'Пароль'), ('NUMBER', 'Числовое поле'), ('DATE', 'Дата и время'), ('CURRENCY', 'Денежная сумма'), ('BOOL', 'Логическое поле'), ('USER', 'ФИО другого участника')], default='TEXT', max_length=10, verbose_name='Тип поля')),
                ('placeholder', models.CharField(max_length=50, verbose_name='Подсказка для заполнения поля')),
                ('checkRegex', models.CharField(blank=True, max_length=200, verbose_name='Регулярное выражение для валидации')),
            ],
        ),
    ]
