# Generated by Django 5.1.6 on 2025-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='placeholder',
            field=models.CharField(blank=True, max_length=50, verbose_name='Подсказка для заполнения поля'),
        ),
    ]
