# Generated by Django 5.1.6 on 2025-04-05 11:41

from django.db import migrations


def create_initial_user_fields(apps, schema_editor):
    Field = apps.get_model('backend', 'Field')

    initial_fields = [
        {
            'name': 'Логин',
            'englName': 'username',
            'placeholder': 'Введите логин',
            'type': 'TEXT',
            'checkRegex': '^[a-zA-Z0-9]+$',
            'relatedItem': "User"
        },
        {
            'name': 'Пароль',
            'englName': 'password',
            'placeholder': 'Введите пароль',
            'type': 'PASSWORD',
            'checkRegex': '^.*(?=.{8,})(?=.*[a-zA-Z])(?=.*\d)(?=.*[!#$%&? "]).*$',
            'relatedItem': "User"
        },
        {
            'name': 'Фамилия',
            'englName': 'last_name',
            'placeholder': 'Ваша фамилия',
            'type': 'TEXT',
            'checkRegex': '^[а-яА-Я]+(-[а-яА-Я]+)*$',
            'relatedItem': "User"
        },
        {
            'name': 'Имя',
            'englName': 'first_name',
            'placeholder': 'Ваше имя',
            'type': 'TEXT',
            'checkRegex': '^[а-яА-Я]+(-[а-яА-Я]+)*$',
            'relatedItem': "User"
        },
        {
            'name': 'Отчество',
            'englName': 'patronymic',
            'placeholder': 'Ваше отчество',
            'type': 'TEXT',
            'checkRegex': '^[а-яА-Я]*$',
            'relatedItem': "User"
        }
    ]

    for field in initial_fields:
        Field.objects.get_or_create(**field)

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_field_checkregex_alter_field_placeholder'),
    ]

    operations = [
        migrations.RunPython(create_initial_user_fields),
    ]
