# Generated by Django 5.1.6 on 2025-03-16 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('showDate', models.DateField()),
                ('doc', models.FileField(upload_to='docs/')),
                ('table', models.JSONField(default=list)),
                ('custom', models.JSONField(default=dict)),
                ('contrator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.contractor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.executor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
