# Generated by Django 5.1.6 on 2025-03-22 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_companyuser_company_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('type', models.CharField(choices=[('ACT', 'Акт'), ('ORDER', 'Заказ'), ('REPORT', 'Отчёт')], max_length=10, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='docs/templates/', verbose_name='Файл шаблона')),
                ('custom', models.JSONField(default=dict, verbose_name='Дополнительные переменные')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.contractor', verbose_name='Связанная компания')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('showDate', models.DateField(verbose_name='Отображаемая дата')),
                ('table', models.JSONField(default=list)),
                ('custom', models.JSONField(default=dict)),
                ('contrator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.contractor', verbose_name='Заказчик')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.executor', verbose_name='Исполнитель')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.template', verbose_name='Шаблон')),
            ],
        ),
    ]
