# Generated by Django 5.1.6 on 2025-03-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('type', models.CharField(choices=[('ACT', 'Акт'), ('ORDER', 'Заказ'), ('REPORT', 'Отчёт')], max_length=10, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='docs/templates/', verbose_name='Файл шаблона')),
                ('variables', models.JSONField(default=list, verbose_name='Переменные шаблона')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('showDate', models.DateField(verbose_name='Отображаемая дата')),
                ('table', models.JSONField(default=list)),
                ('custom', models.JSONField(default=dict)),
                ('contrator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.contractor', verbose_name='Заказчик')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.executor', verbose_name='Исполнитель')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.template', verbose_name='Шаблон')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
