# Generated by Django 5.1.6 on 2025-03-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_template_document_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='variables',
        ),
        migrations.AddField(
            model_name='template',
            name='custom',
            field=models.JSONField(default=dict, verbose_name='Дополнительные переменные'),
        ),
    ]
