# Generated by Django 5.1.6 on 2025-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_template_related_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер документа'),
        ),
    ]
